/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ReportingRouteImport } from './routes/reporting'
import { Route as IngestionRouteImport } from './routes/ingestion'
import { Route as ExtractionRouteImport } from './routes/extraction'
import { Route as ClausesRouteImport } from './routes/clauses'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IngestionUploadRouteImport } from './routes/ingestion.upload'
import { Route as IngestionOcrRouteImport } from './routes/ingestion.ocr'
import { Route as ExtractionTechnicalRouteImport } from './routes/extraction.technical'
import { Route as ExtractionConfidenceRouteImport } from './routes/extraction.confidence'
import { Route as ExtractionCommercialRouteImport } from './routes/extraction.commercial'
import { Route as ClausesIdentificationRouteImport } from './routes/clauses.identification'
import { Route as ClausesClassificationRouteImport } from './routes/clauses.classification'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingRoute = ReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestionRoute = IngestionRouteImport.update({
  id: '/ingestion',
  path: '/ingestion',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractionRoute = ExtractionRouteImport.update({
  id: '/extraction',
  path: '/extraction',
  getParentRoute: () => rootRouteImport,
} as any)
const ClausesRoute = ClausesRouteImport.update({
  id: '/clauses',
  path: '/clauses',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestionUploadRoute = IngestionUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => IngestionRoute,
} as any)
const IngestionOcrRoute = IngestionOcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => IngestionRoute,
} as any)
const ExtractionTechnicalRoute = ExtractionTechnicalRouteImport.update({
  id: '/technical',
  path: '/technical',
  getParentRoute: () => ExtractionRoute,
} as any)
const ExtractionConfidenceRoute = ExtractionConfidenceRouteImport.update({
  id: '/confidence',
  path: '/confidence',
  getParentRoute: () => ExtractionRoute,
} as any)
const ExtractionCommercialRoute = ExtractionCommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => ExtractionRoute,
} as any)
const ClausesIdentificationRoute = ClausesIdentificationRouteImport.update({
  id: '/identification',
  path: '/identification',
  getParentRoute: () => ClausesRoute,
} as any)
const ClausesClassificationRoute = ClausesClassificationRouteImport.update({
  id: '/classification',
  path: '/classification',
  getParentRoute: () => ClausesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/clauses': typeof ClausesRouteWithChildren
  '/extraction': typeof ExtractionRouteWithChildren
  '/ingestion': typeof IngestionRouteWithChildren
  '/reporting': typeof ReportingRoute
  '/users': typeof UsersRoute
  '/clauses/classification': typeof ClausesClassificationRoute
  '/clauses/identification': typeof ClausesIdentificationRoute
  '/extraction/commercial': typeof ExtractionCommercialRoute
  '/extraction/confidence': typeof ExtractionConfidenceRoute
  '/extraction/technical': typeof ExtractionTechnicalRoute
  '/ingestion/ocr': typeof IngestionOcrRoute
  '/ingestion/upload': typeof IngestionUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/clauses': typeof ClausesRouteWithChildren
  '/extraction': typeof ExtractionRouteWithChildren
  '/ingestion': typeof IngestionRouteWithChildren
  '/reporting': typeof ReportingRoute
  '/users': typeof UsersRoute
  '/clauses/classification': typeof ClausesClassificationRoute
  '/clauses/identification': typeof ClausesIdentificationRoute
  '/extraction/commercial': typeof ExtractionCommercialRoute
  '/extraction/confidence': typeof ExtractionConfidenceRoute
  '/extraction/technical': typeof ExtractionTechnicalRoute
  '/ingestion/ocr': typeof IngestionOcrRoute
  '/ingestion/upload': typeof IngestionUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/clauses': typeof ClausesRouteWithChildren
  '/extraction': typeof ExtractionRouteWithChildren
  '/ingestion': typeof IngestionRouteWithChildren
  '/reporting': typeof ReportingRoute
  '/users': typeof UsersRoute
  '/clauses/classification': typeof ClausesClassificationRoute
  '/clauses/identification': typeof ClausesIdentificationRoute
  '/extraction/commercial': typeof ExtractionCommercialRoute
  '/extraction/confidence': typeof ExtractionConfidenceRoute
  '/extraction/technical': typeof ExtractionTechnicalRoute
  '/ingestion/ocr': typeof IngestionOcrRoute
  '/ingestion/upload': typeof IngestionUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/clauses'
    | '/extraction'
    | '/ingestion'
    | '/reporting'
    | '/users'
    | '/clauses/classification'
    | '/clauses/identification'
    | '/extraction/commercial'
    | '/extraction/confidence'
    | '/extraction/technical'
    | '/ingestion/ocr'
    | '/ingestion/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/clauses'
    | '/extraction'
    | '/ingestion'
    | '/reporting'
    | '/users'
    | '/clauses/classification'
    | '/clauses/identification'
    | '/extraction/commercial'
    | '/extraction/confidence'
    | '/extraction/technical'
    | '/ingestion/ocr'
    | '/ingestion/upload'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/clauses'
    | '/extraction'
    | '/ingestion'
    | '/reporting'
    | '/users'
    | '/clauses/classification'
    | '/clauses/identification'
    | '/extraction/commercial'
    | '/extraction/confidence'
    | '/extraction/technical'
    | '/ingestion/ocr'
    | '/ingestion/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  ClausesRoute: typeof ClausesRouteWithChildren
  ExtractionRoute: typeof ExtractionRouteWithChildren
  IngestionRoute: typeof IngestionRouteWithChildren
  ReportingRoute: typeof ReportingRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting': {
      id: '/reporting'
      path: '/reporting'
      fullPath: '/reporting'
      preLoaderRoute: typeof ReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingestion': {
      id: '/ingestion'
      path: '/ingestion'
      fullPath: '/ingestion'
      preLoaderRoute: typeof IngestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extraction': {
      id: '/extraction'
      path: '/extraction'
      fullPath: '/extraction'
      preLoaderRoute: typeof ExtractionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clauses': {
      id: '/clauses'
      path: '/clauses'
      fullPath: '/clauses'
      preLoaderRoute: typeof ClausesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingestion/upload': {
      id: '/ingestion/upload'
      path: '/upload'
      fullPath: '/ingestion/upload'
      preLoaderRoute: typeof IngestionUploadRouteImport
      parentRoute: typeof IngestionRoute
    }
    '/ingestion/ocr': {
      id: '/ingestion/ocr'
      path: '/ocr'
      fullPath: '/ingestion/ocr'
      preLoaderRoute: typeof IngestionOcrRouteImport
      parentRoute: typeof IngestionRoute
    }
    '/extraction/technical': {
      id: '/extraction/technical'
      path: '/technical'
      fullPath: '/extraction/technical'
      preLoaderRoute: typeof ExtractionTechnicalRouteImport
      parentRoute: typeof ExtractionRoute
    }
    '/extraction/confidence': {
      id: '/extraction/confidence'
      path: '/confidence'
      fullPath: '/extraction/confidence'
      preLoaderRoute: typeof ExtractionConfidenceRouteImport
      parentRoute: typeof ExtractionRoute
    }
    '/extraction/commercial': {
      id: '/extraction/commercial'
      path: '/commercial'
      fullPath: '/extraction/commercial'
      preLoaderRoute: typeof ExtractionCommercialRouteImport
      parentRoute: typeof ExtractionRoute
    }
    '/clauses/identification': {
      id: '/clauses/identification'
      path: '/identification'
      fullPath: '/clauses/identification'
      preLoaderRoute: typeof ClausesIdentificationRouteImport
      parentRoute: typeof ClausesRoute
    }
    '/clauses/classification': {
      id: '/clauses/classification'
      path: '/classification'
      fullPath: '/clauses/classification'
      preLoaderRoute: typeof ClausesClassificationRouteImport
      parentRoute: typeof ClausesRoute
    }
  }
}

interface ClausesRouteChildren {
  ClausesClassificationRoute: typeof ClausesClassificationRoute
  ClausesIdentificationRoute: typeof ClausesIdentificationRoute
}

const ClausesRouteChildren: ClausesRouteChildren = {
  ClausesClassificationRoute: ClausesClassificationRoute,
  ClausesIdentificationRoute: ClausesIdentificationRoute,
}

const ClausesRouteWithChildren =
  ClausesRoute._addFileChildren(ClausesRouteChildren)

interface ExtractionRouteChildren {
  ExtractionCommercialRoute: typeof ExtractionCommercialRoute
  ExtractionConfidenceRoute: typeof ExtractionConfidenceRoute
  ExtractionTechnicalRoute: typeof ExtractionTechnicalRoute
}

const ExtractionRouteChildren: ExtractionRouteChildren = {
  ExtractionCommercialRoute: ExtractionCommercialRoute,
  ExtractionConfidenceRoute: ExtractionConfidenceRoute,
  ExtractionTechnicalRoute: ExtractionTechnicalRoute,
}

const ExtractionRouteWithChildren = ExtractionRoute._addFileChildren(
  ExtractionRouteChildren,
)

interface IngestionRouteChildren {
  IngestionOcrRoute: typeof IngestionOcrRoute
  IngestionUploadRoute: typeof IngestionUploadRoute
}

const IngestionRouteChildren: IngestionRouteChildren = {
  IngestionOcrRoute: IngestionOcrRoute,
  IngestionUploadRoute: IngestionUploadRoute,
}

const IngestionRouteWithChildren = IngestionRoute._addFileChildren(
  IngestionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  ClausesRoute: ClausesRouteWithChildren,
  ExtractionRoute: ExtractionRouteWithChildren,
  IngestionRoute: IngestionRouteWithChildren,
  ReportingRoute: ReportingRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
