/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as ReportingRouteImport } from './routes/reporting'
import { Route as IngestionRouteImport } from './routes/ingestion'
import { Route as ExtractionRouteImport } from './routes/extraction'
import { Route as ClausesRouteImport } from './routes/clauses'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersTeamRouteImport } from './routes/users.team'
import { Route as UsersSecurityRouteImport } from './routes/users.security'
import { Route as ReportingSummaryRouteImport } from './routes/reporting.summary'
import { Route as ReportingExportRouteImport } from './routes/reporting.export'
import { Route as ReportingDiscrepancyRouteImport } from './routes/reporting.discrepancy'
import { Route as IngestionUploadRouteImport } from './routes/ingestion.upload'
import { Route as IngestionOcrRouteImport } from './routes/ingestion.ocr'
import { Route as ExtractionTechnicalRouteImport } from './routes/extraction.technical'
import { Route as ExtractionConfidenceRouteImport } from './routes/extraction.confidence'
import { Route as ExtractionCommercialRouteImport } from './routes/extraction.commercial'
import { Route as ExtractionClausesRouteImport } from './routes/extraction.clauses'
import { Route as ClausesIdentificationRouteImport } from './routes/clauses.identification'
import { Route as ClausesClassificationRouteImport } from './routes/clauses.classification'
import { Route as ChatSummarizeRouteImport } from './routes/chat.summarize'
import { Route as ChatQueryRouteImport } from './routes/chat.query'
import { Route as ChatAssistantRouteImport } from './routes/chat.assistant'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingRoute = ReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestionRoute = IngestionRouteImport.update({
  id: '/ingestion',
  path: '/ingestion',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractionRoute = ExtractionRouteImport.update({
  id: '/extraction',
  path: '/extraction',
  getParentRoute: () => rootRouteImport,
} as any)
const ClausesRoute = ClausesRouteImport.update({
  id: '/clauses',
  path: '/clauses',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersTeamRoute = UsersTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => UsersRoute,
} as any)
const UsersSecurityRoute = UsersSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => UsersRoute,
} as any)
const ReportingSummaryRoute = ReportingSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => ReportingRoute,
} as any)
const ReportingExportRoute = ReportingExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => ReportingRoute,
} as any)
const ReportingDiscrepancyRoute = ReportingDiscrepancyRouteImport.update({
  id: '/discrepancy',
  path: '/discrepancy',
  getParentRoute: () => ReportingRoute,
} as any)
const IngestionUploadRoute = IngestionUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => IngestionRoute,
} as any)
const IngestionOcrRoute = IngestionOcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => IngestionRoute,
} as any)
const ExtractionTechnicalRoute = ExtractionTechnicalRouteImport.update({
  id: '/technical',
  path: '/technical',
  getParentRoute: () => ExtractionRoute,
} as any)
const ExtractionConfidenceRoute = ExtractionConfidenceRouteImport.update({
  id: '/confidence',
  path: '/confidence',
  getParentRoute: () => ExtractionRoute,
} as any)
const ExtractionCommercialRoute = ExtractionCommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => ExtractionRoute,
} as any)
const ExtractionClausesRoute = ExtractionClausesRouteImport.update({
  id: '/clauses',
  path: '/clauses',
  getParentRoute: () => ExtractionRoute,
} as any)
const ClausesIdentificationRoute = ClausesIdentificationRouteImport.update({
  id: '/identification',
  path: '/identification',
  getParentRoute: () => ClausesRoute,
} as any)
const ClausesClassificationRoute = ClausesClassificationRouteImport.update({
  id: '/classification',
  path: '/classification',
  getParentRoute: () => ClausesRoute,
} as any)
const ChatSummarizeRoute = ChatSummarizeRouteImport.update({
  id: '/summarize',
  path: '/summarize',
  getParentRoute: () => ChatRoute,
} as any)
const ChatQueryRoute = ChatQueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => ChatRoute,
} as any)
const ChatAssistantRoute = ChatAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/clauses': typeof ClausesRouteWithChildren
  '/extraction': typeof ExtractionRouteWithChildren
  '/ingestion': typeof IngestionRouteWithChildren
  '/reporting': typeof ReportingRouteWithChildren
  '/upload': typeof UploadRoute
  '/users': typeof UsersRouteWithChildren
  '/chat/assistant': typeof ChatAssistantRoute
  '/chat/query': typeof ChatQueryRoute
  '/chat/summarize': typeof ChatSummarizeRoute
  '/clauses/classification': typeof ClausesClassificationRoute
  '/clauses/identification': typeof ClausesIdentificationRoute
  '/extraction/clauses': typeof ExtractionClausesRoute
  '/extraction/commercial': typeof ExtractionCommercialRoute
  '/extraction/confidence': typeof ExtractionConfidenceRoute
  '/extraction/technical': typeof ExtractionTechnicalRoute
  '/ingestion/ocr': typeof IngestionOcrRoute
  '/ingestion/upload': typeof IngestionUploadRoute
  '/reporting/discrepancy': typeof ReportingDiscrepancyRoute
  '/reporting/export': typeof ReportingExportRoute
  '/reporting/summary': typeof ReportingSummaryRoute
  '/users/security': typeof UsersSecurityRoute
  '/users/team': typeof UsersTeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/clauses': typeof ClausesRouteWithChildren
  '/extraction': typeof ExtractionRouteWithChildren
  '/ingestion': typeof IngestionRouteWithChildren
  '/reporting': typeof ReportingRouteWithChildren
  '/upload': typeof UploadRoute
  '/users': typeof UsersRouteWithChildren
  '/chat/assistant': typeof ChatAssistantRoute
  '/chat/query': typeof ChatQueryRoute
  '/chat/summarize': typeof ChatSummarizeRoute
  '/clauses/classification': typeof ClausesClassificationRoute
  '/clauses/identification': typeof ClausesIdentificationRoute
  '/extraction/clauses': typeof ExtractionClausesRoute
  '/extraction/commercial': typeof ExtractionCommercialRoute
  '/extraction/confidence': typeof ExtractionConfidenceRoute
  '/extraction/technical': typeof ExtractionTechnicalRoute
  '/ingestion/ocr': typeof IngestionOcrRoute
  '/ingestion/upload': typeof IngestionUploadRoute
  '/reporting/discrepancy': typeof ReportingDiscrepancyRoute
  '/reporting/export': typeof ReportingExportRoute
  '/reporting/summary': typeof ReportingSummaryRoute
  '/users/security': typeof UsersSecurityRoute
  '/users/team': typeof UsersTeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/clauses': typeof ClausesRouteWithChildren
  '/extraction': typeof ExtractionRouteWithChildren
  '/ingestion': typeof IngestionRouteWithChildren
  '/reporting': typeof ReportingRouteWithChildren
  '/upload': typeof UploadRoute
  '/users': typeof UsersRouteWithChildren
  '/chat/assistant': typeof ChatAssistantRoute
  '/chat/query': typeof ChatQueryRoute
  '/chat/summarize': typeof ChatSummarizeRoute
  '/clauses/classification': typeof ClausesClassificationRoute
  '/clauses/identification': typeof ClausesIdentificationRoute
  '/extraction/clauses': typeof ExtractionClausesRoute
  '/extraction/commercial': typeof ExtractionCommercialRoute
  '/extraction/confidence': typeof ExtractionConfidenceRoute
  '/extraction/technical': typeof ExtractionTechnicalRoute
  '/ingestion/ocr': typeof IngestionOcrRoute
  '/ingestion/upload': typeof IngestionUploadRoute
  '/reporting/discrepancy': typeof ReportingDiscrepancyRoute
  '/reporting/export': typeof ReportingExportRoute
  '/reporting/summary': typeof ReportingSummaryRoute
  '/users/security': typeof UsersSecurityRoute
  '/users/team': typeof UsersTeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/clauses'
    | '/extraction'
    | '/ingestion'
    | '/reporting'
    | '/upload'
    | '/users'
    | '/chat/assistant'
    | '/chat/query'
    | '/chat/summarize'
    | '/clauses/classification'
    | '/clauses/identification'
    | '/extraction/clauses'
    | '/extraction/commercial'
    | '/extraction/confidence'
    | '/extraction/technical'
    | '/ingestion/ocr'
    | '/ingestion/upload'
    | '/reporting/discrepancy'
    | '/reporting/export'
    | '/reporting/summary'
    | '/users/security'
    | '/users/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/clauses'
    | '/extraction'
    | '/ingestion'
    | '/reporting'
    | '/upload'
    | '/users'
    | '/chat/assistant'
    | '/chat/query'
    | '/chat/summarize'
    | '/clauses/classification'
    | '/clauses/identification'
    | '/extraction/clauses'
    | '/extraction/commercial'
    | '/extraction/confidence'
    | '/extraction/technical'
    | '/ingestion/ocr'
    | '/ingestion/upload'
    | '/reporting/discrepancy'
    | '/reporting/export'
    | '/reporting/summary'
    | '/users/security'
    | '/users/team'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/clauses'
    | '/extraction'
    | '/ingestion'
    | '/reporting'
    | '/upload'
    | '/users'
    | '/chat/assistant'
    | '/chat/query'
    | '/chat/summarize'
    | '/clauses/classification'
    | '/clauses/identification'
    | '/extraction/clauses'
    | '/extraction/commercial'
    | '/extraction/confidence'
    | '/extraction/technical'
    | '/ingestion/ocr'
    | '/ingestion/upload'
    | '/reporting/discrepancy'
    | '/reporting/export'
    | '/reporting/summary'
    | '/users/security'
    | '/users/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRouteWithChildren
  ClausesRoute: typeof ClausesRouteWithChildren
  ExtractionRoute: typeof ExtractionRouteWithChildren
  IngestionRoute: typeof IngestionRouteWithChildren
  ReportingRoute: typeof ReportingRouteWithChildren
  UploadRoute: typeof UploadRoute
  UsersRoute: typeof UsersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting': {
      id: '/reporting'
      path: '/reporting'
      fullPath: '/reporting'
      preLoaderRoute: typeof ReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingestion': {
      id: '/ingestion'
      path: '/ingestion'
      fullPath: '/ingestion'
      preLoaderRoute: typeof IngestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extraction': {
      id: '/extraction'
      path: '/extraction'
      fullPath: '/extraction'
      preLoaderRoute: typeof ExtractionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clauses': {
      id: '/clauses'
      path: '/clauses'
      fullPath: '/clauses'
      preLoaderRoute: typeof ClausesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/team': {
      id: '/users/team'
      path: '/team'
      fullPath: '/users/team'
      preLoaderRoute: typeof UsersTeamRouteImport
      parentRoute: typeof UsersRoute
    }
    '/users/security': {
      id: '/users/security'
      path: '/security'
      fullPath: '/users/security'
      preLoaderRoute: typeof UsersSecurityRouteImport
      parentRoute: typeof UsersRoute
    }
    '/reporting/summary': {
      id: '/reporting/summary'
      path: '/summary'
      fullPath: '/reporting/summary'
      preLoaderRoute: typeof ReportingSummaryRouteImport
      parentRoute: typeof ReportingRoute
    }
    '/reporting/export': {
      id: '/reporting/export'
      path: '/export'
      fullPath: '/reporting/export'
      preLoaderRoute: typeof ReportingExportRouteImport
      parentRoute: typeof ReportingRoute
    }
    '/reporting/discrepancy': {
      id: '/reporting/discrepancy'
      path: '/discrepancy'
      fullPath: '/reporting/discrepancy'
      preLoaderRoute: typeof ReportingDiscrepancyRouteImport
      parentRoute: typeof ReportingRoute
    }
    '/ingestion/upload': {
      id: '/ingestion/upload'
      path: '/upload'
      fullPath: '/ingestion/upload'
      preLoaderRoute: typeof IngestionUploadRouteImport
      parentRoute: typeof IngestionRoute
    }
    '/ingestion/ocr': {
      id: '/ingestion/ocr'
      path: '/ocr'
      fullPath: '/ingestion/ocr'
      preLoaderRoute: typeof IngestionOcrRouteImport
      parentRoute: typeof IngestionRoute
    }
    '/extraction/technical': {
      id: '/extraction/technical'
      path: '/technical'
      fullPath: '/extraction/technical'
      preLoaderRoute: typeof ExtractionTechnicalRouteImport
      parentRoute: typeof ExtractionRoute
    }
    '/extraction/confidence': {
      id: '/extraction/confidence'
      path: '/confidence'
      fullPath: '/extraction/confidence'
      preLoaderRoute: typeof ExtractionConfidenceRouteImport
      parentRoute: typeof ExtractionRoute
    }
    '/extraction/commercial': {
      id: '/extraction/commercial'
      path: '/commercial'
      fullPath: '/extraction/commercial'
      preLoaderRoute: typeof ExtractionCommercialRouteImport
      parentRoute: typeof ExtractionRoute
    }
    '/extraction/clauses': {
      id: '/extraction/clauses'
      path: '/clauses'
      fullPath: '/extraction/clauses'
      preLoaderRoute: typeof ExtractionClausesRouteImport
      parentRoute: typeof ExtractionRoute
    }
    '/clauses/identification': {
      id: '/clauses/identification'
      path: '/identification'
      fullPath: '/clauses/identification'
      preLoaderRoute: typeof ClausesIdentificationRouteImport
      parentRoute: typeof ClausesRoute
    }
    '/clauses/classification': {
      id: '/clauses/classification'
      path: '/classification'
      fullPath: '/clauses/classification'
      preLoaderRoute: typeof ClausesClassificationRouteImport
      parentRoute: typeof ClausesRoute
    }
    '/chat/summarize': {
      id: '/chat/summarize'
      path: '/summarize'
      fullPath: '/chat/summarize'
      preLoaderRoute: typeof ChatSummarizeRouteImport
      parentRoute: typeof ChatRoute
    }
    '/chat/query': {
      id: '/chat/query'
      path: '/query'
      fullPath: '/chat/query'
      preLoaderRoute: typeof ChatQueryRouteImport
      parentRoute: typeof ChatRoute
    }
    '/chat/assistant': {
      id: '/chat/assistant'
      path: '/assistant'
      fullPath: '/chat/assistant'
      preLoaderRoute: typeof ChatAssistantRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatAssistantRoute: typeof ChatAssistantRoute
  ChatQueryRoute: typeof ChatQueryRoute
  ChatSummarizeRoute: typeof ChatSummarizeRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatAssistantRoute: ChatAssistantRoute,
  ChatQueryRoute: ChatQueryRoute,
  ChatSummarizeRoute: ChatSummarizeRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface ClausesRouteChildren {
  ClausesClassificationRoute: typeof ClausesClassificationRoute
  ClausesIdentificationRoute: typeof ClausesIdentificationRoute
}

const ClausesRouteChildren: ClausesRouteChildren = {
  ClausesClassificationRoute: ClausesClassificationRoute,
  ClausesIdentificationRoute: ClausesIdentificationRoute,
}

const ClausesRouteWithChildren =
  ClausesRoute._addFileChildren(ClausesRouteChildren)

interface ExtractionRouteChildren {
  ExtractionClausesRoute: typeof ExtractionClausesRoute
  ExtractionCommercialRoute: typeof ExtractionCommercialRoute
  ExtractionConfidenceRoute: typeof ExtractionConfidenceRoute
  ExtractionTechnicalRoute: typeof ExtractionTechnicalRoute
}

const ExtractionRouteChildren: ExtractionRouteChildren = {
  ExtractionClausesRoute: ExtractionClausesRoute,
  ExtractionCommercialRoute: ExtractionCommercialRoute,
  ExtractionConfidenceRoute: ExtractionConfidenceRoute,
  ExtractionTechnicalRoute: ExtractionTechnicalRoute,
}

const ExtractionRouteWithChildren = ExtractionRoute._addFileChildren(
  ExtractionRouteChildren,
)

interface IngestionRouteChildren {
  IngestionOcrRoute: typeof IngestionOcrRoute
  IngestionUploadRoute: typeof IngestionUploadRoute
}

const IngestionRouteChildren: IngestionRouteChildren = {
  IngestionOcrRoute: IngestionOcrRoute,
  IngestionUploadRoute: IngestionUploadRoute,
}

const IngestionRouteWithChildren = IngestionRoute._addFileChildren(
  IngestionRouteChildren,
)

interface ReportingRouteChildren {
  ReportingDiscrepancyRoute: typeof ReportingDiscrepancyRoute
  ReportingExportRoute: typeof ReportingExportRoute
  ReportingSummaryRoute: typeof ReportingSummaryRoute
}

const ReportingRouteChildren: ReportingRouteChildren = {
  ReportingDiscrepancyRoute: ReportingDiscrepancyRoute,
  ReportingExportRoute: ReportingExportRoute,
  ReportingSummaryRoute: ReportingSummaryRoute,
}

const ReportingRouteWithChildren = ReportingRoute._addFileChildren(
  ReportingRouteChildren,
)

interface UsersRouteChildren {
  UsersSecurityRoute: typeof UsersSecurityRoute
  UsersTeamRoute: typeof UsersTeamRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersSecurityRoute: UsersSecurityRoute,
  UsersTeamRoute: UsersTeamRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRouteWithChildren,
  ClausesRoute: ClausesRouteWithChildren,
  ExtractionRoute: ExtractionRouteWithChildren,
  IngestionRoute: IngestionRouteWithChildren,
  ReportingRoute: ReportingRouteWithChildren,
  UploadRoute: UploadRoute,
  UsersRoute: UsersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
